clusterName: __aks_cluster__
cloudProvider: azure
distribution: aks

splunkPlatform:
  endpoint: "https://http-inputs-starbucks.splunkcloud.com/services/collector/event"
  index: "***"

splunkObservability:
  realm: us1
  profilingEnabled: true

secret:
  create: true
  name: starship-splunk-otel-secret

agent:
  enabled: true
  config:


    processors:
      batch:

    exporters:
      signalfx:
        access_token: "${SPLUNK_ACCESS_TOKEN}"
        realm: us1
        ingest_url: "https://ingest.us1.signalfx.com"
        api_url: "https://api.us1.signalfx.com"
        sync_host_metadata: true

      logging:
        loglevel: debug

    connectors:
      spanmetrics:
        metrics_exporter: signalfx
        dimensions:
          - name: store.id
          - name: http.user_agent
          - name: workflow
          - name: displaymonitor.event
          - name: reco.itemcount
          - name: app.version
          - name: error.message
          - name: displaymonitor.status
          - name: displaymonitor.count
          - name: rpc.grpc.status_code
          - name: db.mongodb.collection
          - name: rpc.method
          - name: rpc.service
          - name: error
          - name: db.statement
          - name: k8s.namespace.name
          - name: k8s.cluster.name
          - name: rpc.system
          - name: starship.domain
          - name: starship.docservice.siteid
          - name: starship.docservice.doctype
          - name: starship.userid
          - name: starship.jobservice.route
          - name: reco.variantid
        aggregation_temporality: AGGREGATION_TEMPORALITY_DELTA
        histogram:
          boundaries: [1, 10, 50, 100, 250, 500, 1000, 2500, 5000, 10000]
        exemplars:
          enabled: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [spanmetrics, otlphttp, signalfx]

        metrics:
          receivers: [spanmetrics]
          processors: [batch]
          exporters: [signalfx]
